#!/usr/bin/bash
# (ar)ch (pa)ckages — wrapper script for Arch Linux package tasks

help_prnt () {
  echo ""${0##*/}" [option] [*package] — wrapper script for Arch Linux package tasks
  -e, --explicit - install a package as explicit
  -g, --get      - get/download package upgrade(s) : -G get pkg upgrades all
  -i, --install  - install a package               : -I install as dependency
  -l, --list     - list package files              : -L list pkgs installed
  -o, --owns     - owning package of a file
  -n, --info     - information for a package
  -q, --query    - query for an installed package  : -Q query w/ description
  -r, --remove   - remove a pkg and its deps       : -R force, no argue orphs
  -s, --search   - search for a package            : -S search w/ description
  -u, --upgrade  - upgrade system                  : -U upgrade AUR
  -y, --sync     - sync package db"; exit 2; }

# regular user privilege escalation program
if (( $EUID )); then
  hash sudo 2>&- && sudo=sudo; fi

case $1 in
  -e | --explicit )
    shift; [ $# -gt 0 ] || help_prnt; $sudo pacman -S --asexplicit "$@" ;;
  -g | --get )
    shift; [ $# -gt 0 ] || help_prnt; $sudo pacman -Sw "$@" ;;
  -G | --getup )
    $sudo pacman -Syuw ;;
  -h | --help )
    help_prnt ;;
  -i | --install )
    shift; [ $# -gt 0 ] || help_prnt
    pre="[a-z,A-Z,0-9,@,/,\.\_\+\-]*pkg.tar[.]\?\(gz\|xz\|bz2\|lrz\|lzo\|Z\)\?"
    pkgoff=$(echo "$@" | sed "s/$pre//g")
    pkgloc=$(echo "$@" | grep -o "$pre")
      [ -n "$pkgoff" ] &&       trizen -S $pkgoff
      [ -n "$pkgloc" ] && $sudo pacman -U $pkgloc ;;
  -I | --depinst )
    shift; [ $# -gt 0 ] || help_prnt
    pre="[a-z,A-Z,0-9,@,/,\.\_\+\-]*pkg.tar[.]\?\(gz\|xz\|bz2\|lrz\|lzo\|Z\)\?"
    pkgoff=$(echo "$@" | sed "s/$pre//g")
    pkgloc=$(echo "$@" | grep -o "$pre")
      [ -n "$pkgoff" ] && $sudo pacman -S --asdeps $pkgoff
      [ -n "$pkgloc" ] && $sudo pacman -U --asdeps $pkgloc ;;
  -l | --list )
    shift; [ $# -gt 0 ] || help_prnt; pacman -Qql "$@" ;;
  -L | --pkglist )
    date=$(date +%F)
    pkglist_loc="$(pacman -Qqm)"
    if [ "$pkglist_loc" ] ; then
      echo "$pkglist_loc"                   >| pkglist-loc_"$date" && echo \
        pkglist-loc_"$date"
      pacman -Qqen | grep -v "$pkglist_loc" >| pkglist-off_"$date" && echo \
        pkglist-off_"$date"
    else
      pacman -Qqen                          >| pkglist-off_"$date" && echo \
        pkglist-off_"$date"
    fi ;;
  -o | --own )
    shift; [ $# -gt 0 ] || help_prnt; pacman -Qo  "$@" ;;
  -n | --info )
    shift; [ $# -gt 0 ] || help_prnt
    trizen -Si "$@"   ;;
  -q | --query )
    shift; [ $# -gt 0 ] || help_prnt
    for p in $@; do
      pacman -Qqs "$p";done ;;
  -Q | --Query )
    shift; [ $# -gt 0 ] || help_prnt
    for p in $@; do
      pacman -Qi  "$p";done ;;
  -r | --remove )
    shift
    if [ "$#" -eq 0 ]; then
      extrpkg=$(pacman -Qtdq)
      [ "$extrpkg" ] && $sudo pacman -Rcs $extrpkg
    else
      $sudo pacman -Rs "$@"; fi ;;
  -R | --forcerm )
    shift; [ $# -gt 0 ] || help_prnt; $sudo pacman -Rdd "$@" ;;
  -s | --search )
    shift; [ $# -gt 0 ] || help_prnt
    trizen -Ssq "$@" ;;
  -S | --Search )
    shift; [ $# -gt 0 ] || help_prnt
    trizen -Ss "$@"  ;;
  -u | --upgrade )
    $sudo pacman -Syu ;;
  -U | --upaur )
    trizen -Su --aur --devel ;;
  -y | --sync )
    $sudo pacman -Syy ;;
  * ) help_prnt       ;;
esac
